name: Reusable workflow example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
      url_path:
          required: true
          type: string
      
    # secrets:
    #   token:
    #     required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - name: run hellow world
      run: echo "Hello world"  >> $GITHUB_STEP_SUMMARY 
    
    - name: print branch name
      run: echo "${{ github.ref }}" >> $GITHUB_STEP_SUMMARY
      
    - name: print var
      run: |
         echo "##Workflow Path"  >> $GITHUB_STEP_SUMMARY
         echo "${{ inputs.config-path }}"  >> $GITHUB_STEP_SUMMARY

    - name: show repo url
      run: |
         echo '### Hello world! 🚀' >> $GITHUB_STEP_SUMMARY  
         ID=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID
         echo "$ID" >> $GITHUB_STEP_SUMMARY  
         echo "Job status: ${{ job.status }}" >> $GITHUB_STEP_SUMMARY
         echo "https://docs.github.com/en/actions/using-workflows/${{ inputs.url_path }}" >> $GITHUB_STEP_SUMMARY