name: demo_Aarush 
on: push
jobs:
    first_job:
       runs-on: ubuntu-latest
       steps:
       - name: step1 
         run: echo "Heelo world"
         
       - uses: ./.github/workflows/demo123.yaml
         with:
            config-path: "hello sunny"
            url_path: "workflow-commands-for-github-actions"